### ISSUE TITLE
:headding-anchor visible in content

### ISSUE THREAD

**Issue by wimsymons** [AdobeDocs/experience-manager-release-information.en#12]
Issue in ./help/using/update-releases-roadmap.md

Maybe search and replace gone wrong? heading -> headding?

**Comment by wimsymons** [comment]
Just noticed it is on **ALL** pages below https://experienceleague.adobe.com/en/docs/experience-manager-65

**Comment by guillaumecarlino** [comment]
It has been fixed by the platform team. Thanks.
