### ISSUE TITLE
Packageshare links to SD

### ISSUE THREAD

**Issue by ashishguptaiitb** [AdobeDocs/experience-manager-release-information.en#4]
Issue in ./help/home.md
Many articles in the repo contains links to adobeaemcloud.com. Not all but some point to software that is not EOL. Update the download links of the active offering with SD links.

**Comment by ashishguptaiitb** [comment]
Folks, it seems that this issue is resolved. Please check once. 
Also, if and where present (outside of comments), these links to PS will now be broken links, so may be it is a bug and not an enh.

**Comment by guillaumecarlino** [comment]
Fixing this
