### ISSUE TITLE
Release notes- redirection issue

### ISSUE THREAD

**Issue by Pulkit-Jain-Adobe** [AdobeDocs/experience-manager-release-information.en#9]
Issue in ./help/aem-forms-releases.md

AEM Forms URL for 6.5.15 redirecting to incorrect release notes page. 
It should redirect to 6.5.15 release notes, instead of this it is redirecting to 6.5.16 release notes.

Label: DocBugBlitz2023

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
I updated the links.
